### ISSUE TITLE
Policy hostpaths-psp settings are not a list

### ISSUE THREAD

**Issue by kravciak** [kubewarden/ui#236]
UI generates policy settings that are allow `pathPrefix` value. Policy settings `Allow host path` require list instead.

Policy server won't start policy with wrong settings
```
ERROR policy_server::worker_pool: cannot validate policy settings error=[clusterwide-hppsp] 
  settings are not valid: Some("pathPrefix key is missing; pathPrefix key is missing")
```
### Current Behavior

Yaml currently generated by UI
```yaml
settings:
  allowedHostPaths:
    pathPrefix: /foo
    readOnly: false
```

### Expected Behavior

Yaml required by the policy should have this format:
```yaml
settings:
  allowedHostPaths:
  - pathPrefix: "/foo"
    readOnly: true
  - ...
```

![Screenshot from 2023-02-10 09-45-32](https://user-images.githubusercontent.com/538604/218045198-60632dc7-8ae0-4f2d-8f74-61923a581f65.png)
