### ISSUE TITLE
Verify Image Signatures: invalid type: map, expected a sequence

### ISSUE THREAD

**Issue by kravciak** [kubewarden/ui#239]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

Invalid yaml produced by UI
```yaml
  settings:
    description: null
    rule: PublicKey
    modifyImagesWithDigest: true
    signatures:
      image: theimage
      keyless:
        issuer: ''
        subject: ''
```

### Expected Behavior

Valid yaml example from policy readme
```yaml
signatures:
- image: "ghcr.io/kubewarden/*"
  githubActions:
    owner: "kubewarden"
```
