### ISSUE TITLE
Selinux PSP: RunAsMany is set multiple times

### ISSUE THREAD

**Issue by kravciak** [kubewarden/ui#240]
### Current Behavior

When I select rule: RunAsAny there is checkbox called the same - produces yaml that is accepted by policy, but not relevant to the settings.
Values in yaml: valid `rule: RunAsAny` and extra `RunAsAny: true`

```yaml
settings:
  description: null
  rule: RunAsAny
  MustRunAs:
    user: ''
    role: ''
    type: ''
    level: 0
  RunAsAny: true
```

### Expected Behavior

Valid settings
```yaml
# example 1
rule: RunAsAny

# example 2
rule: MustRunAs
user: user
role: role
type: type
level: s0:c0,c6
```

### Anything else?

![Screenshot from 2023-02-10 13-28-10](https://user-images.githubusercontent.com/538604/218092990-ad85a677-4df2-4e30-8c38-5faab1a51217.png)
