### ISSUE TITLE
Environment Variable Policy: invalid type: map, expected a sequence

### ISSUE THREAD

**Issue by kravciak** [kubewarden/ui#241]
### Current Behavior

[Policy readme](https://github.com/kubewarden/environment-variable-policy#examples) defines rules as a list. Policy created in UI fails to start.

```
settings are not valid: Some("Error invoking settings validation callback: GuestCallFailure(\"Error decoding validation payload {\\\"description\\\":null,\\\"rules\\\":{\\\"environmentVariables\\\":{\\\"name\\\":\\\"\\\",\\\"value\\\":\\\"\\\"},\\\"reject\\\":\\\"anyIn\\\"}}: Error(\\\"invalid type: map, expected a sequence\\\", line: 1, column: 28)\")"), 
```
Invalid yaml from UI:
```yaml
  settings:
    description: null
    rules:
      reject: anyIn
      environmentVariables:
        name: thename
        value: theval
```

### Expected Behavior

Valid rules are a list:
```yaml
settings:
  rules:
    - reject: anyIn
      environmentVariables:
        - name: "envvar1"
          value: "envvar1_value"
        - name: "envvar2"
          value: "envvar2_value"
```
