### ISSUE TITLE
Default policy server is missing KUBEWARDEN_ENABLE_METRICS env

### ISSUE THREAD

**Issue by kravciak** [kubewarden/ui#287]
### Current Behavior

Kubewarden defaults chart is missing `KUBEWARDEN_ENABLE_METRICS` env variable when telemetry is enabled on controller.
This variable is set when I create custom policy server.

There are 2 ways how to create policy server.

1. default one -> install rancher-kubewarden-defaults chart by `InstalChart button` shown in policy servers overview info box
User has to edit yaml and and manually enable telemetry to get any metrics.

```
policyServer:
  env:
    - name: KUBEWARDEN_LOG_LEVEL
      value: info
  telemetry:
    enabled: false
...
```

2. custom policy server -> go to policy server list and click `Create` button
User do not need to change anything, metrics are enabled by env variable
```
spec:
  env:
    - name: KUBEWARDEN_ENABLE_METRICS
      value: '1'
    - name: KUBEWARDEN_LOG_FMT
...
```

### Expected Behavior

When telemetry is enabled on controller then it's automatically enabled also on new policy servers (both default and custom)

[Docs](https://docs.kubewarden.io/operator-manual/ui-extension/metrics) says it's required only to enable telemetry on kubewarden-controller, it does not mention policy-servers. We should either:
- add requirement to enable telemetry on existing policy servers
- enable it automatically when user edit kubewarden-controller resource
