### ISSUE TITLE
Flexvolume Drivers Psp: wrong yaml

### ISSUE THREAD

**Issue by kravciak** [kubewarden/ui#293]
### Current Behavior

Config example from [README](https://artifacthub.io/packages/kubewarden/flexvolume-drivers-psp/flexvolume-drivers-psp):
```yaml
settings:
  allowedFlexVolumes:
    - driver: example/lvm
    - driver: example/cifs
```

Config generated by UI:
```yaml
  settings:
    allowed_flex_volumes:
      key1: val1
      key2: val2
```

Generated config is not a list. Also it seems that `key` should always be `driver`.
