### ISSUE TITLE
User Group PSP: Can not add range, `Add` button is broken

### ISSUE THREAD

**Issue by kravciak** [kubewarden/ui#296]
### Current Behavior

When I click `Add` button nothing happens but in YAML I see some min/max ranges added under wrong key
```yaml
  settings:
    run_as_user:
      rule: MustRunAs
      overwrite: false
    run_as_group:
      rule: ''
    supplemental_groups:
      rule: ''
    run_as_user.ranges:
      - min: 0
        max: 0
      - min: 0
        max: 0
      - min: 0
        max: 0
```
