### ISSUE TITLE
Selinux PSP: Invalid YAML

### ISSUE THREAD

**Issue by kravciak** [kubewarden/ui#298]
### Current Behavior

Setting produced by UI:
```yaml
settings:
  description: null
  rule: MustRunAs
  MustRunAs:
    - user: fasd
      role: fads
      type: fdas
      level: 0
    - user: '213'
      role: '321'
      type: '321'
      level: 0
```

Valid YAML:
```yaml
settings:
  rule: MustRunAs
  user: user
  role: role
  type: type
  level: s0:c0,c6
```

Also field `level` allows only numbers, but in example it's `s0:c0,c6`

### Expected Behavior

- Level field is not a number
- Fixed YAML for rule: `MustRunAs`
